### ISSUE TITLE
Fix AWS instance id launch delay 

### ISSUE THREAD

**Issue by sjoshi6** [alt-code/AutoSpark#17]

**Comment by sjoshi6** [comment]
KeyPair:172.31.39.113
Traceback (most recent call last):
  File "ec2_connector.py", line 265, in <module>
    main(sys.argv[1:])
  File "ec2_connector.py", line 250, in main
    wait_for_public_ip(reservation)
  File "ec2_connector.py", line 123, in wait_for_public_ip
    while instance.update() != "running":
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/instance.py", line 413, in update
    rs = self.connection.get_all_reservations([self.id], dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 681, in get_all_reservations
    [('item', Reservation)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance ID 'i-80937944' does not exist</Message></Error></Errors><RequestID>592f0b4c-f4cd-4589-8c07-b51205eabb4f</RequestID></Response>

**Comment by chrisparnin** [comment]
Some projects to reference:
https://github.com/p31-d3ng/HW/blob/master/HW1/hw1.js

**Comment by sjoshi6** [comment]
## AWS uses an eventual consistency model.

- 10% of times the boto module is expected to fail due to consistency lag while creating bulk instances.
- Best solution available online is to add a hardcoded wait between run_instances and call for instance_id

Solution:
- Added **time.sleep(60)** to the code.
